### ISSUE TITLE
rockchip平台mjpeg解码

### ISSUE THREAD

**Issue by zuoshouxin123** [alanlilyan/codeschool-alan#1]
请问您在rockchip平台上用mpp实现mjpeg解码成功了吗？

**Comment by alandingbc** [comment]
> 请问您在rockchip平台上用mpp实现mjpeg解码成功了吗？

对比起项目比较久，我也不太记得细节了。印象中，设置正确应该可以解码。
另外，相关问题您最好去rockhip对应项目提问，以下为参考：

[mpp mjpeg](https://github.com/rockchip-linux/mpp/issues/82)
